language: csharp
solution: Quaver.sln
os:
- osx
env:
global:
- Configuration=Public

install:
- wget -O MonoGame.pkg "http://teamcity.monogame.net/guestAuth/repository/download/MonoGame_PackageMacAndLinux/.lastSuccessful/MonoGame.pkg?branch_MonoGame=%3Cdefault%3E"
- sudo installer -pkg "MonoGame.pkg" -target /

script:
- nuget Quaver.sln
- msbuild Quaver/Quaver.csproj /p:Configuration=Public /v:d /t:Build