namespace Quaver.Shared.Input.Global;

public enum GlobalKeybindActions
{
    Screenshot,
    OpenOptions,
    ToggleFullscreen,
    TogglePause,
    CycleFpsLimiter,
    ToggleOnlineHub,
    ReloadSkin,
    Back,
    IncreaseRate,
    DecreaseRate,
    TogglePitch,
    RemoveMods,
    ToggleMirror,
    IncreaseScrollSpeed,
    DecreaseScrollSpeed,
    IncreaseLocalScrollSpeed,
    DecreaseLocalScrollSpeed,
    IncreaseOffset,
    DecreaseOffset,
    IncreaseOffsetSmall,
    DecreaseOffsetSmall,
    GameplayPause,
    GameplayPauseUp,
    GameplayPauseDown,
    GameplayToggleScoreboard,
    GameplayToggleOverlay,
    GameplayRetry,
    ResultsRetry,
    ResultsTab,
    DialogConfirm,
    DialogCancel,
}
