using Quaver.Shared.Config;
using Quaver.Shared.Input.Global;

namespace Quaver.Shared.Screens.V2.Options.Catalog.Categories
{
    internal static class AdvancedOptions
    {
        internal static OptionsRowGroup[] Create() => new[]
        {
            new OptionsRowGroup(OptionsCategoryId.Advanced, "Screen_Options_Video",
                OptionsRowDefinition.Toggle("Screen_Options_LowerFPSOnInactiveWindow",
                    ConfigManager.LowerFpsOnWindowInactive),
                OptionsRowDefinition.Toggle("Screen_Options_EnableHighProcessPriority",
                    ConfigManager.EnableHighProcessPriority),
                OptionsRowDefinition.Slider("Screen_Options_EditorImGuiScale",
                    ConfigManager.EditorImGuiScalePercentage, value => $"{value}%"),
                OptionsRowDefinition.Slider("Screen_Options_EditorImGuiFontSize", ConfigManager.EditorImGuiFontSize,
                    value => $"{value}px")),
            new OptionsRowGroup(OptionsCategoryId.Advanced, "Screen_Options_Audio",
                OptionsRowDefinition.Toggle("Screen_Options_UseSmoothAudioFrameTimingDuringGameplay",
                    ConfigManager.SmoothAudioTimingGameplay)),
            new OptionsRowGroup(OptionsCategoryId.Advanced, "Screen_Options_Gameplay",
                OptionsRowDefinition.Toggle("Screen_Options_DisplayGameplayOverlay",
                    ConfigManager.DisplayGameplayOverlay),
                OptionsRowDefinition.Toggle("Screen_Options_DisplayNotificationsDuringGameplay",
                    ConfigManager.DisplayNotificationsInGameplay),
                OptionsRowDefinition.Toggle("Screen_Options_ShowSpectators", ConfigManager.ShowSpectators),
                OptionsRowDefinition.Toggle("Screen_Options_DisplayRankedAccuracyWithCustomJudgements",
                    ConfigManager.DisplayRankedAccuracy),
                OptionsRowDefinition.Slider("Screen_Options_HitErrorFadeTime", ConfigManager.HitErrorFadeTime,
                    value => $"{value / 1000f:0.0} sec"),
                OptionsRowDefinition.Toggle("Screen_Options_HitErrorEarlyLateColoring",
                    ConfigManager.ColorHitErrorByTiming),
                OptionsRowDefinition.Slider("Screen_Options_HitErrorEarlyLateWindow",
                    ConfigManager.HitErrorEarlyLateWindow, value => $"{value} ms"),
                OptionsRowDefinition.Toggle("Screen_Options_EnableComboAlerts", ConfigManager.DisplayComboAlerts),
                OptionsRowDefinition.Toggle("Screen_Options_DisplayUnbeatableScores",
                    ConfigManager.DisplayUnbeatableScoresDuringGameplay),
                OptionsRowDefinition.Toggle("Screen_Options_KeepPlayingUponFailing",
                    ConfigManager.KeepPlayingUponFailing),
                OptionsRowDefinition.Slider("Screen_Options_NormaliseScrollVelocityByRatePercentage",
                    ConfigManager.NormaliseScrollVelocityByRatePercentage, value => $"{value}%")),
            new OptionsRowGroup(OptionsCategoryId.Advanced, "Screen_Options_Skin",
                OptionsRowDefinition.Toggle("Screen_Options_Display1v1TournamentOverlay",
                    ConfigManager.Display1v1TournamentOverlay),
                OptionsRowDefinition.Toggle("Screen_Options_Display1v1PlayfieldScores",
                    ConfigManager.TournamentDisplay1v1PlayfieldScores),
                OptionsRowDefinition.Toggle("Screen_Options_ReloadSkinOnChange", ConfigManager.ReloadSkinOnChange)),
            new OptionsRowGroup(OptionsCategoryId.Advanced, "Screen_Options_Input",
                OptionsRowDefinition.Keybind("Screen_Options_TogglePlaytestAutoplay",
                    GlobalKeybindActions.GameplayTogglePlaytestAutoplay),
                OptionsRowDefinition.Toggle("Screen_Options_InvertEditorScrolling",
                    ConfigManager.InvertEditorScrolling),
                OptionsRowDefinition.Toggle("Screen_Options_InvertScrolling", ConfigManager.InvertScrolling)),
            new OptionsRowGroup(OptionsCategoryId.Advanced, "Screen_Options_Miscellaneous",
                OptionsRowDefinition.Toggle("Screen_Options_AutomaticallyLogIntoTheServer",
                    ConfigManager.AutoLoginToServer),
                OptionsRowDefinition.Toggle("Screen_Options_DisplaySongRequestNotifications",
                    ConfigManager.DisplaySongRequestNotifications),
                OptionsRowDefinition.Toggle("Screen_Options_DisplayWarningForPausing",
                    ConfigManager.DisplayPauseWarning),
                OptionsRowDefinition.Toggle("Screen_Options_DisplayWarningForFailing", ConfigManager.DisplayFailWarning),
                OptionsRowDefinition.Toggle("Screen_Options_DisplayEpilepsyWarning",
                    ConfigManager.DisplayEpilepsyWarning),
                OptionsRowDefinition.Toggle("Screen_Options_DisplayMenuAudioVisualizer",
                    ConfigManager.DisplayMenuAudioVisualizer),
                OptionsRowDefinition.Toggle("Screen_Options_DisplayFailedLocalScores",
                    ConfigManager.DisplayFailedLocalScores),
                OptionsRowDefinition.Toggle("Screen_Options_DeleteOriginalFileAfterImport",
                    ConfigManager.DeleteOriginalFileAfterImport),
                OptionsRowDefinition.Toggle("Screen_Options_DiscordRichPresence", ConfigManager.DiscordRichPresence),
                OptionsRowDefinition.Toggle("Screen_Options_DisplayRankedAccuracyForLocalLeaderboards",
                    ConfigManager.LeaderboardRankedAccuracy))
        };
    }
}
